apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: private-registry
        image: registry:2
        volumeMounts:
        - name: registrystorage
          mountPath: "/var/lib/registry"
        ports:
          - containerPort: 30001
      volumes:
      - name: registrystorage
        persistentVolumeClaim:
          claimName: registrystorage
