apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
  labels:
    app: db
spec:
  secretName: mysql
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 2
  datadirVolumeClaimTemplate:
    storageClassName: standard
    accessModes: 
      - ReadWriteMany
    resources:
      requests:
        storage: 3Gi
