apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mysql
  tlsUseSelfSigned: true
  instances: 1
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    storageClassName: standard
    accessModes: 
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
