apiVersion: v1           
kind: ServiceAccount  
metadata:                                                                                                                                                                 
  name: jenkins-admin

---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins-admin
type: kubernetes.io/service-account-token
